application: calendarer
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  script: calendarer.py
  
- url: /.*
  script: calendarer.py
  login: required

